### ISSUE TITLE
SNC ! off by one character in BOM-encoded file

### ISSUE THREAD

**Issue by markjm** [JoshuaKGoldberg/TypeStat#1013]
🐛 Bug Report
TypeStat version: 0.5.2
TypeScript version: 4.4.4
Node version: 16.x

Seems files with BOM encoding mess up the character position for SNC. Perhaps this is an "issue" (using the term loosely) with Typescript's character position reporting @DanielRosenwasser?

Reproduction
https://github.com/markjm/demos-by-commit/tree/typestat-demo-3

**Comment by JoshuaKGoldberg** [comment]
Closing off as an old `external` issue. Please let me know if there's anything TypeStat should do!
