### ISSUE TITLE
What does adding better types to typescript file mean ?

### ISSUE THREAD

**Issue by TedSean** [JoshuaKGoldberg/TypeStat#1039]
Hey,

I just had a silly question, when you are saying it adds better types to typescript file, what does that mean ? Does it mean it just adds needed config in tsconfig file or it adds type annotation in the `.tsx` file.

**Comment by JoshuaKGoldberg** [comment]
:wave: Hi! Great question! If you have to ask, it means there's definitely work to be done to improve TypeStat's documentation. 

TypeStat's primary two use cases are to:
* Convert `.js`/`.jsx` files to `.ts`/`.tsx`
* Add & change type annotations in `.ts`/`.tsx` files

From the README.md, the `.js`/`.jsx` conversion is the first ✨, and the type annotations are the following three:

> ✨ Convert JavaScript files to TypeScript in a single bound!
> ✨ Add TypeScript types on files freshly converted from JavaScript to TypeScript!
> ✨ Infer types to fix --noImplicitAny and --noImplicitThis violations!
> ✨ Annotate missing nulls and undefineds to get you started with --strictNullChecks!
