### ISSUE TITLE
🚀 Feature: Set static version to cli when building

### ISSUE THREAD

**Issue by rubiesonthesky** [JoshuaKGoldberg/TypeStat#1485]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/TypeStat/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

I'm proposing that `version` would be set on compile time to `runCli`. This would remove need for reading one more file when running the tool. The version should not change between runs. :)

This can be done either by custom esbuild plugin or using some existing esbuild plugin. tsup should support them: 

- [tsup: Custom esbuild plugin and options](https://tsup.egoist.dev/#custom-esbuild-plugin-and-options). 
- [esbuild: Custom plugins](https://esbuild.github.io/plugins/#using-plugins)

One example plugin

- [esbuild-plugin-environment](https://github.com/webdeveric/esbuild-plugin-environment/tree/master)

### Additional Info

Custom plugin could look like this for example:

```ts
import { defineConfig } from "tsup";

import { version } from "./package.json";

const versionPlugin = {
	name: "versionPlugin",
	setup(build: any) {
		return Object.assign((build.initialOptions.define ??= {}), {
			"process.env.VERSION": JSON.stringify(version),
		});
	},
};

export default defineConfig({
	bundle: false,
	clean: true,
	dts: true,
	entry: ["src/**/*.ts", "!src/**/*.test.*"],
	esbuildPlugins: [versionPlugin],
	format: "esm",
	outDir: "lib",
	sourcemap: true,
});

```

And then we refer to the environment variable in `runCli.ts`: 

```ts
	if ({}.hasOwnProperty.call(rawOptions, "version")) {
		runtime.output.stdout(process.env.VERSION ?? "development");
		return ResultStatus.Succeeded;
	}
```

In the output `rucCli.js` file, this is just

```js
  if ({}.hasOwnProperty.call(rawOptions, "version")) {
    runtime.output.stdout("0.7.3");
    return ResultStatus.Succeeded;
  }
```

**Comment by JoshuaKGoldberg** [comment]
> need for reading one more file

Why is that need bad? It's only a few ms, no?

**Comment by JoshuaKGoldberg** [comment]
Cool! I think we're roughly on the same page for the short-term stuff then - no need to change this now. Thanks for the ideation! 🤗 

For long-term, I think the #1341 -> #1314 area of work is top of mind for me: splitting into an _enhancement_ package and an _initialization_ package. But:

> really fast cli tool. And it could be even installed with homebrew or used with dprint as a wasm

I don't think that's going to happen 😞. It'd be great, but both the _enhancement_ (especially) and the _initialization_ parts of things will need to use TypeScript type info to be useful. So no matter what sub-second-scale improvements we make prior to that, the TypeScript bottleneck is likely to be orders of magnitudes slower. Even if the nice enhancements native speed tools such as Biome, `deno lint`, and Oxc are working on (https://www.joshuakgoldberg.com/blog/rust-based-javascript-linters-fast-but-no-typed-linting-right-now) come to fruition.
