### ISSUE TITLE
🐛 Bug: bin missing from package.json and bin/typestat pointing to wrong place?

### ISSUE THREAD

**Issue by rubiesonthesky** [JoshuaKGoldberg/TypeStat#1496]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/TypeStat/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

Before create-typescript-app migration, there was this is package.json

```json
	"bin": {
		"typestat": "bin/typestat"
	},
```

No it's no longer there.

Also `bin/typestat` should be changed to import from `"../lib/cli/runCli"`? 

### Actual

- bin is missing

### Additional Info

I'm trying to understand how I could run development build locally, but not succeeding. 

I also think there are a lot unnecessary files in the npm package, looking at here: https://www.npmjs.com/package/typestat?activeTab=code - that was releaset before create-typescript-app migration, so it may be that the situation is now different.

- .github
- .husky
- eslint stuff
- git stuff
- prettier stuff
- jest
- dependaconfig
- renovate.json (There is another renovate.json in .github, I think there should be only one?)
- tsconfig.json (I have understood that this should never go to packages?)

**Comment by JoshuaKGoldberg** [comment]
Heh in retrospect I should have asked for your review on #1435. I was nervous to take up more of your time given how awesome you've already been. But, yeah, there are a lot of little things I missed there that should be cleaned up. Accepting PRs for whatever you can spot!

**Comment by pjonsson** [comment]
I tried the 0.7.3 release first, but hit some bug, so then I tried to run typestat from the main branch in the repository without any success. This bug seems pretty important for being able to run typestat from the repository, is the suggested fix broken, or is something else blocking that from being merged?

**Comment by JoshuaKGoldberg** [comment]
Just me procrastinating picking this repository's maintenance back up. 🙂
