### ISSUE TITLE
🛠️ Tooling: use ts-api-utils or ts checkers instead of own methods

### ISSUE THREAD

**Issue by rubiesonthesky** [JoshuaKGoldberg/TypeStat#1544]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/TypeStat/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

My suggestion is to use more helper methods and check methods from `ts-api-utils` and `typescript` when they already exits there.

For example, instead of doing check `node.parent.operatorToken.kind === ts.SyntaxKind.EqualsToken`, use `isEqualsToken(node.parent.operatorToken)` from `ts-api-utils`.

**Comment by JoshuaKGoldberg** [comment]
Yeah +1. A lot of those checks didn't exist when I first started working on TypeStat.

My preference would be to use TypeScript's first, then `ts-api-utils` as a fallback.
