### ISSUE TITLE
📝 Documentation: document how to run TypeStat in-place in repository

### ISSUE THREAD

**Issue by pjonsson** [JoshuaKGoldberg/TypeStat#2022]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/TypeStat/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

I don't know TypeScript/JavaScript, but I would like to add a print statement somewhere in the source code and then run TypeStat on a third-party project. I spent a couple of hours yesterday trying to achieve this, and I was at best mildly successful; I couldn't get HEAD of the main branch to run at all so in the end I checked out the 0.7.3 release and manually added the PR that fixed the crash, edited something else in-place and then "ran" that. The reason I call it mildly successful is because that gave me the help message so things "worked", but `bin/typestat -c ../otherrepo/typestat.json` failed with some other error message that I didn't look into since 0.7.3 is quite different from HEAD.

It's more than likely that I didn't do the right thing to run TypeStat, or that my failure to run things was because #1508 wasn't merged yet, but I would like to take human error out of the equation by having a short section that gives the commands to run the uncommitted changes in the TypeStat repository on a third-party repository.

I think having the commands documented would enable drive-by contributions where someone might be able to fix/troubleshoot their problem if they could get to the fixing part directly without having to first learn the ecosystem.

**Comment by JoshuaKGoldberg** [comment]
I think this is a reasonable request, sure. But just checking, have you looked at https://github.com/JoshuaKGoldberg/TypeStat/blob/main/.github/DEVELOPMENT.md#building?

The general flow I use is:

1. Build per those docs (`pnpm build --watch`)
2. Run `node ../path/to/typestat/bin/typestat.mjs` from the local repo
