### ISSUE TITLE
Make respecting PropTypes opt-in

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/TypeStat#260]
Kind of the flip side of #198. I've found that inferences from PropTypes tend to overly rely on `any` and `Function`, often as optional props, because prop types tend to not have a high level of fidelity. Until #257 and related issues are improved, I think inferring from PropTypes should be opt-in as a last ditch kind of scenario.

**Comment by JoshuaKGoldberg** [comment]
Fixed in #300. They're still opt-out for now but can easily be made opt-in with hints.

**Comment by devinrhode2** [comment]
I was trying to get typestat to migrate react prop types (remove `FooComp.propTypes = {...}` and `import ... from 'prop-types'`) but wasn't able to get it to work. (I had hints.react.propTypes: "always" and the other setting was explicitly set to "asWritten")

I ended up using ts-migrate `react-props` plugin like so:
```
yarn add ts-migrate@0.1.23 --dev
yarn ts-migrate migrate . --plugin react-props
yarn ts-migrate migrate . --plugin hoist-class-statics
yarn ts-migrate migrate . --plugin react-default-props
yarn ts-migrate migrate . --plugin react-shape
yarn ts-migrate migrate . --plugin jsdoc
```

Just sharing here in case others are also digging around GH issues :)

**Comment by JoshuaKGoldberg** [comment]
@devinrhode2 thanks for the heads up! If you have the time, I would love an issue on TypeStat so I could investigate what went wrong inside TypeStat on your project! 👀
