### ISSUE TITLE
Incorrect return type for react functional component

### ISSUE THREAD

**Issue by danstiner** [JoshuaKGoldberg/TypeStat#291]
In the following example there seems to be a clear bug that the inferred type for the `props` parameter is used as the return type of the function. The return type should be a React component type I think.

Also a smaller annoyance, the inferred type of the props parameter is quite verbose, I'm not sure but perhaps `props: React.ButtonHTMLAttributes<HTMLButtonElement>` would be still correct but much more succinct?

```
button.js

const Button = props => (<button type="button" {...props}>Button</button>)
```

After the conversion:

````
button.ts

const Button = (props: JSX.IntrinsicAttributes & React.ClassAttributes<HTMLButtonElement> & React.ButtonHTMLAttributes<HTMLButtonElement>): JSX.IntrinsicAttributes & React.ClassAttributes<HTMLButtonElement> & React.ButtonHTMLAttributes<HTMLButtonElement> => (
  <button type="button" {...props}>
    Button
  </button>
)
```

**Comment by JoshuaKGoldberg** [comment]
👋 @danstiner! Would you be able to post the `typestat.json` you were using for this? I'm (finally!) taking a look and not able to repro any badness here.
